### ISSUE TITLE
Custom form elements problem. 

### ISSUE THREAD

**Issue by lucassmacedo** [demsking/vue-json-schema-demo-elementui#1]
Hello, first, thanks for this awesome package!
I have trying with Element UI, works fine with input text, but when i set a select or checkbox, the selected values dont show.
I have trying with the original example
git@github.com:demsking/vue-json-schema-demo-elementui.git

**Comment by demsking** [comment]
I just released [`vue-json-schema@1.1.0`](https://github.com/demsking/vue-json-schema/releases/tag/v1.1.0) with a fix. I've also update the demo project
